name: 'Aplica tests sobre los fuentes IV'
description: 'Actuando sobre el fuente, lleva a cabo una serie de tests para comprobar objetivos alcanzados'
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/dist/iv-checks-on-source.pl
      shell: bash
