name: Test Perl utility library
on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing
  steps:
    - name: root suid tar
      run: sudo chown root /bin/tar && sudo chmod u+s /bin/tar
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install cpanminus
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: cpanminus
    - name: Cache dependencies
      id: cache-cpanfile
      uses: actions/cache@v4
      with:
        path: /usr/local/share/perl/5.38.2
        key: ${{ runner.os }}-cpanfile-sudo
    - name: Install dependencies
      if: steps.cache-cpanfiles.outputs.cache-hit != 'true'
      run: cpanm --sudo -v --installdeps .
    - name: Test perl
      run: prove
