name: Test Perl utility library
on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install cpanminus
      uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cpanminus
    - name: Install dependencies
      run: cpanm --installdeps .
    - name: Test perl
      run: prove
