name: Test Perl utility library
on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install cpanminus
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: cpanminus
    - name: Cache dependencies
      id: cache-cpanfile
      uses: actions/cache@v4
      with:
        path: ~/perl5
        key: ${{ runner.os }}-cpanfile
    - name: Install dependencies
      if: steps.cache-cpanfiles.outputs.cache-hit != 'true'
      run: cpanm -v --installdeps .
    - name: Test perl
      run: prove -l ~/perl5 t
